default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: password
  pool: 5

development:
  <<: *default
  database: datarade_challenge_development

test:
  <<: *default
  database: datarade_challenge_test
